title: My GitHub Blog
description: A simple blog powered by Jekyll and GitHub Pages
theme: minima

# Navigation
header_pages:
  - index.md
  - about.md
  - blog.md

# Plugins (optional but recommended)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

